### ISSUE TITLE
Error running deepify server

### ISSUE THREAD

**Issue by dam0** [MitocGroup/deep-microservices-helloworld#11] opened 2015-12-19 00:21 UTC
> if [ -d 'hooks/' ]; then hooks/assure_deep_dev.js; fi

Error while listing deep modules: Error: ENOENT: no such file or directory, scandir '/Users/*/Development/Projects/temp/deep-hello-world/DeepHelloWorld/Backend/src/SayHello/node_modules/deep-framework/node_modules'
npm WARN say-hello-test@0.0.1 No repository field.
npm WARN say-hello-test@0.0.1 No license field.
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/nvm/0.29.0/versions/node/v4.1.2/bin/node" "/usr/local/opt/nvm/versions/node/v4.1.2/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! deep-framework@1.5.6 postinstall: `if [ -d 'hooks/' ]; then hooks/assure_deep_dev.js; fi`
npm ERR! Exit status 1

**Comment by eistrati** [comment] 2015-12-19 15:56
@dam0 Thanks for reporting this issue! We'll try to resolve it asap.

**Comment by dam0** [comment] 2015-12-20 00:05
Got it working under node v4.1.2, perhaps related to git rsa permissions under osx?

**Comment by dam0** [comment] 2015-12-20 00:23
running 'deepify server' on node 5.3.0, error thrown on request:

11:20:18 GMT+1100 (AEDT) Running Lambda arn:aws:lambda:us-west-2:123456789012:function:hello.world.example-sample-say-hello with payload {"Name":"damo"}
11:20:19 GMT+1100 (AEDT) [Error: Module version mismatch. Expected 47, got 46.]
11:20:19 GMT+1100 (AEDT) { [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
11:20:19 GMT+1100 (AEDT) { [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
11:20:19 GMT+1100 (AEDT) [Error: Module version mismatch. Expected 47, got 46.]
11:20:19 GMT+1100 (AEDT) { [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
11:20:19 GMT+1100 (AEDT) { [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
/usr/local/lib/node_modules/deepify/node_modules/deep-db/lib.compiled/Local/Driver/AbstractDriver.js:73
        throw error;
        ^

Error: Cannot find module 'xmlbuilder'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Proxyquire._require 

etc' ...

**Comment by eistrati** [comment] 2015-12-20 18:11
Preliminary thoughts: npm v2 vs npm v3 has major architectural differences on how the dependencies are resolved, so it might be related to the way `deepify server` pulls them through `npm install`. We are still working to identify the root cause, and as soon as we get a clear picture, will update this thread. I hope, for the time being, you're able to use this repo with npm v2 and node v4 ;)

**Comment by eistrati** [comment] 2016-02-24 16:49
This ticket has been solved. We're closing it now. Please feel free to reopen if you experience this issue again.

**Closed as completed by eistrati** 2016-02-24 16:49 UTC
